# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-15 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LOGIN_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='Apparently had no name', max_length=45)),
                ('lname', models.CharField(default='Apparently had no name', max_length=45)),
                ('notes', models.TextField(default='not much to say I guess')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fan', models.ManyToManyField(related_name='favorite_author', to='LOGIN_APP.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='A title would go here, but you forgot', max_length=45)),
                ('description', models.TextField(default='A description would go here, but you forgot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ManyToManyField(default=1, related_name='books', to='BOOK_APP.Authors')),
                ('fan', models.ManyToManyField(related_name='favorite_book', to='LOGIN_APP.Users')),
            ],
        ),
    ]
