# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-15 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN_APP', '0001_initial'),
        ('BOOK_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='contributer',
            field=models.ManyToManyField(related_name='added_author', to='LOGIN_APP.Users'),
        ),
        migrations.AddField(
            model_name='books',
            name='contributer',
            field=models.ManyToManyField(related_name='added_book', to='LOGIN_APP.Users'),
        ),
    ]
