# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-15 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOOK_APP', '0002_auto_20190715_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='contributer',
            new_name='contributor',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='contributer',
            new_name='contributor',
        ),
    ]
